# Generated by Django 3.2.7 on 2021-09-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordFormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fireno', models.CharField(max_length=50)),
                ('ipc', models.CharField(max_length=50)),
            ],
        ),
    ]
