# Generated by Django 3.1.2 on 2021-09-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0009_recordformdata_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordformdata',
            name='district',
        ),
        migrations.AlterField(
            model_name='recordformdata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
